In [108]:
## LIST   []

In [101]:
fruits = ['orange', 'apple', 'pear', 'banana', 'kiwi', 'apple', 'banana']
type(fruits)

list

In [102]:
len(fruits)

7

In [103]:
fruits[0]

'orange'

In [104]:
fruits[-7]

'orange'

In [105]:
fruits[:]

['orange', 'apple', 'pear', 'banana', 'kiwi', 'apple', 'banana']

In [106]:
fruits[2:5]

['pear', 'banana', 'kiwi']

In [4]:
a = [4,65,7,3,5,6,8,3,2,1,6]
a

[4, 65, 7, 3, 5, 6, 8, 3, 2, 1, 6]

In [5]:
b = [1, "p", 5, 8.999, 74]
b

[1, 'p', 5, 8.999, 74]

In [9]:
type(b[3])

float

In [7]:
type(b)

list

In [21]:
fruits = ['orange', 'apple', 'pear', 'banana', 'kiwi', 'apple', 'banana']
type(fruits)

list

In [22]:
fruits.append("pineapple")

In [23]:
fruits

['orange', 'apple', 'pear', 'banana', 'kiwi', 'apple', 'banana', 'pineapple']

In [24]:
fruits.count('banana')

2

In [25]:
fruits.remove("apple")
fruits

['orange', 'pear', 'banana', 'kiwi', 'apple', 'banana', 'pineapple']

In [32]:
fruits.index("banana")

4

In [29]:
fruits.pop(2)
fruits

['orange', 'pear', 'kiwi', 'apple', 'banana', 'pineapple']

In [39]:
fruits.sort()
fruits

['apple', 'banana', 'kiwi', 'orange', 'pear', 'pineapple']

In [42]:
fruits.reverse()
fruits

['pineapple', 'pear', 'orange', 'kiwi', 'banana', 'apple']

In [44]:
fruits[2:6]

['orange', 'kiwi', 'banana', 'apple']

In [45]:
numeros = [0, 1, 2, 3, 4, 5]

In [47]:
x = []
for i in numeros:
    x.append(i**2)
print(x)

[0, 1, 4, 9, 16, 25]


In [49]:
y = [x**2 for x in numeros]
print(y)

[0, 1, 4, 9, 16, 25]


In [ ]:
## Tupla ()

In [64]:
b = ((1, 0, 0), (0, 1, 0), (0, 0, 1))
b

((1, 0, 0), (0, 1, 0), (0, 0, 1))

In [54]:
type(b[0])

tuple

In [61]:
b = [[1, 0, 0], (0, 1, 0), (0, 0, 1)]
b

[[1, 0, 0], (0, 1, 0), (0, 0, 1)]

In [62]:
b[1][2]

0

In [55]:
a = (1, 2, 3)

In [56]:
b = [1, 2, 3]

In [57]:
a

(1, 2, 3)

In [60]:
a.remove(1)

AttributeError: 'tuple' object has no attribute 'remove'

In [58]:
b

[1, 2, 3]

In [59]:
b.remove(1)
b

[2, 3]

In [65]:
tarifa = [("onibus", "SP", 10), ("onibus", "RJ", 9), 
          ("onibus", "ZZ", 5), ("taxi", "RJ", 15),
          ("taxi", "AL", 50),
          ("taxi", "SP", 20), ("taxi", "ZZ", 30)]

In [66]:
tarifa

[('onibus', 'SP', 10),
 ('onibus', 'RJ', 9),
 ('onibus', 'ZZ', 5),
 ('taxi', 'RJ', 15),
 ('taxi', 'AL', 50),
 ('taxi', 'SP', 20),
 ('taxi', 'ZZ', 30)]

In [70]:
tipo = input("tipo de transporte: ")
estado = input("Estado: ")

q = 0
for i in tarifa:
    q+=1
    if i[0] == tipo:
        if i[1] == estado:
            print("tarifa", estado, i[2])
            break
        else:
            if i[1] == "ZZ":
                print("tarifa", estado, i[2])
                break
print("registros lidos", q)

tipo de transporte: onibus
Estado: RR
tarifa RR 5
registros lidos 3


In [107]:
## DICT

In [99]:
tarifa_dict = {"onibus": {'RJ': 9,
                          'SP': 10,
                          'ZZ': 5},
               "taxi": {'RJ': 15,
                        'SP': 20,
                        'AL': 50,
                        'ZZ': 30}}
tarifa_dict

{'onibus': {'RJ': 9, 'SP': 10, 'ZZ': 5},
 'taxi': {'RJ': 15, 'SP': 20, 'AL': 50, 'ZZ': 30}}

In [97]:
del tarifa_dict["onibus"]

In [98]:
tarifa_dict

{'taxi': {'RJ': 15, 'SP': 20, 'AL': 50, 'ZZ': 30}}

In [92]:
tarifa_dict.items()

dict_items([('onibus', {'RJ': 9, 'SP': 10, 'ZZ': 5}), ('taxi', {'RJ': 15, 'SP': 20, 'AL': 50, 'ZZ': 30})])

In [95]:
tarifa_dict.values()

dict_values([{'RJ': 9, 'SP': 10, 'ZZ': 5}, {'RJ': 15, 'SP': 20, 'AL': 50, 'ZZ': 30}])

In [94]:
tarifa_dict['onibus'].values()

dict_values([9, 10, 5])

In [74]:
tarifa_dict.keys()

dict_keys(['onibus', 'taxi'])

In [75]:
tarifa_dict["onibus"].keys()

dict_keys(['RJ', 'SP', 'ZZ'])

In [77]:
tarifa_dict["onibus"]['SP']

10

In [78]:
tarifa_dict.get("onibus")

{'RJ': 9, 'SP': 10, 'ZZ': 5}

In [83]:
x = tarifa_dict["onibus"].get("DD")
if not x:
    print("ok")

ok


In [84]:
tipo = input("tipo de transporte: ")
estado = input("Estado: ")

if tarifa_dict.get(tipo):
    if tarifa_dict[tipo].get(estado):
        print(estado, tarifa_dict[tipo].get(estado))
    else:
        print(estado, tarifa_dict[tipo].get("ZZ"))

tipo de transporte: onibus
Estado: RR
RR 5


In [87]:
estado = input("Estado: ")

for tipo in tarifa_dict.keys():
    if tarifa_dict[tipo].get(estado):
        print(estado, tipo)

Estado: AL
AL taxi


In [109]:
## SET   {}

In [131]:
frutas = {"maçã", "banana", "cereja"}
type(frutas)

set

In [132]:
frutas

{'banana', 'cereja', 'maçã'}

In [133]:
frutas.add("laranja")
frutas

{'banana', 'cereja', 'laranja', 'maçã'}

In [134]:
frutas.add("abacate")
frutas

{'abacate', 'banana', 'cereja', 'laranja', 'maçã'}

In [126]:
frutas.remove("banana")
frutas

{'abacate', 'cereja', 'laranja', 'maçã'}

In [127]:
frutas.discard("banana")
frutas

{'abacate', 'cereja', 'laranja', 'maçã'}

In [128]:
frutas.discard("laranja")
frutas

{'abacate', 'cereja', 'maçã'}

In [135]:
fruta_removida = frutas.pop()
fruta_removida

'banana'

In [136]:
frutas

{'abacate', 'cereja', 'laranja', 'maçã'}

In [138]:
frutas.clear()
frutas

set()

In [139]:
conjunto1 = {1, 2, 3}
conjunto2 = {3, 4, 5}
uniao = conjunto1.union(conjunto2)
uniao

{1, 2, 3, 4, 5}

In [140]:
intersecao = conjunto1.intersection(conjunto2)
intersecao

{3}

In [142]:
diferenca = conjunto1.difference(conjunto2)
diferenca

{1, 2}

In [143]:
diferenca = conjunto2.difference(conjunto1)
diferenca

{4, 5}

In [144]:
subconjunto = {1, 2}
resultado = subconjunto.issubset(conjunto1)
resultado

True

In [145]:
resultado = conjunto1.issuperset(subconjunto)
resultado

True

In [146]:
diff_simetrica = conjunto1.symmetric_difference(conjunto2)
diff_simetrica

{1, 2, 4, 5}

In [147]:
A = {1, 2, 3, 4}
B = {3, 4, 5, 6}

# União
print(A | B)  # {1, 2, 3, 4, 5, 6}

# Interseção
print(A & B)  # {3, 4}

# Diferença
print(A - B)  # {1, 2}

# Diferença Simétrica
print(A ^ B)  # {1, 2, 5, 6}

{1, 2, 3, 4, 5, 6}
{3, 4}
{1, 2}
{1, 2, 5, 6}


In [148]:
5 in A

False

In [150]:
for i in (A | B):
    print(i)

1
2
3
4
5
6


In [151]:
A[0]

TypeError: 'set' object is not subscriptable

In [152]:
A

{1, 2, 3, 4}

In [153]:
A_list = list(A)

In [154]:
A_list[0]

1

In [155]:
3 in A

True

In [156]:
A_list.count(3)

1

In [157]:
A_list.index(3)

2

In [158]:
A_list[2]

3

In [165]:
A=[[1,2,3], [4,5,6], [7, 8, 9]]

#printa as linhas da matriz A
for i in A:
    print(i)
print("\n")

A_t=[[k[0] for k in A], [k[1] for k in A], [k[2] for k in A]]

#printa as linhas da transposta de A
for i in A_t:
    print(i)

[1, 2, 3]
[4, 5, 6]
[7, 8, 9]


[1, 4, 7]
[2, 5, 8]
[3, 6, 9]


In [180]:
A=[[1,2], [4,5], [7, 8]]

#printa as linhas da matriz A
for i in A:
    print(i)
print("\n")

A_t=[[k[0] for k in A], [k[1] for k in A]]

#printa as linhas da transposta de A
for i in A_t:
    print(i)

[1, 2]
[4, 5]
[7, 8]


[1, 4, 7]
[2, 5, 8]


In [182]:
import numpy as np

A = np.array([[1,2], [4,5], [7, 8]])

A_t = np.transpose(A)

print(A)
print("\n")
print(A_t)

[[1 2]
 [4 5]
 [7 8]]


[[1 4 7]
 [2 5 8]]


In [183]:
A.T

array([[1, 4, 7],
       [2, 5, 8]])