In [1]:
import pandas as pd
import numpy as np

In [ ]:
import pandas as pd
import numpy as np

def process(df):
    no_results = [
        'Nenhum resultado disponível',
        'Os resultados para este evento podem ser acessados através da sua Página Oficial.'
    ]
    
    # transpose data frame
    data = df.T
    
    # rename & drop unnecessary columns 
    data = data.drop(columns = "url_details")
    data = data.rename(columns = {
        "data": "date",
        "categories": "json"
    })
    
    # remove entries where race results aren't available
    data = data[~data["json"].isin(no_results)]
    
    # extract the race distance and explode dataframe
    data["race_distance"] = data.apply(lambda df: list(df["json"].keys()), axis = 1)
    data = data.explode("race_distance")
    
    # select race info for each distance
    data["json"] = data.apply(lambda df: df["json"][df["race_distance"]], axis = 1)
    
    # extract group category and explode dataframe
    data["category"] = data.apply(lambda df: list(df["json"].keys()), axis = 1)
    data = data.explode("category")
    
    # select race info for each distance + category
    data["json"] = data.apply(lambda df: df["json"][df["category"]], axis = 1)
    
    # extract information about each athlete
    def extract_athletes(df):
        athletes = []
        try:
            for athlete in df["json"]["athletes"]:
                athletes.append(list(athlete.values()))

            return athletes
        except:
            return np.NaN
        
    data["athletes"] = data.apply(extract_athletes, axis = 1)
    data = data.explode("athletes")

In [14]:
pip install xgboost

python(42383) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.


   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.9/1.9 MB 7.1 MB/s eta 0:00:0000:0100:01
Note: you may need to restart the kernel to use updated packages.


In [17]:
import pandas as pd

# read the entire file into a python array
with open('PI_request_data.json', 'rb') as f:
   data = f.readlines()

## remove the trailing "\n" from each line
data = map(lambda x: x.rstrip(), data)

In [9]:
data_json_str = "[" + ",".join(data) + "]"

# now, load it into pandas
data_df = pd.read_json(data_json_str)

TypeError: sequence item 0: expected str instance, bytes found

In [19]:

import pandas as pd

exercise = {
    "Duration": {
        "0": 60,
        "1": 60,
        "2": 60,
        "3": 45,
        "4": 45,
        "5": 60
    },
    "Pulse": {
        "0": 110,
        "1": 117,
        "2": 103,
        "3": 109,
        "4": 117,
        "5": 102
    },
    "Calories": {
        "0": 409,
        "1": 479,
        "2": 340,
        "3": 282,
        "4": 406,
        "5": 300
    }
}

data = pd.DataFrame(exercise)

print(data)



   Duration  Pulse  Calories
0        60    110       409
1        60    117       479
2        60    103       340
3        45    109       282
4        45    117       406
5        60    102       300


In [20]:
data = pd.DataFrame(data)

In [21]:
data

Duration  Pulse  Calories
0        60    110       409
1        60    117       479
2        60    103       340
3        45    109       282
4        45    117       406
5        60    102       300

In [72]:
import pandas as pd

caminho_do_arquivo_csv = 'Data_Sky_Completo.csv'

df = pd.read_csv(caminho_do_arquivo_csv, sep=';')

#df['vdm_1000'] = df['varia_dia_media'] * float(1000)
#df['vda_1000'] = df['varia_dia_abs'] * float(1000)

df.head(36)

product_id product                              description date_period  \
0         1001  67212Q        LUBRAX ESSENCIAL SL 15W40 1-LITRO  01/01/2024   
1         1001  67212Q        LUBRAX ESSENCIAL SL 15W40 1-LITRO  01/02/2024   
2         1001  67212Q        LUBRAX ESSENCIAL SL 15W40 1-LITRO  01/03/2024   
3         1001  67212Q        LUBRAX ESSENCIAL SL 15W40 1-LITRO  01/04/2024   
4         1001  67212Q        LUBRAX ESSENCIAL SL 15W40 1-LITRO  01/05/2024   
5         1001  67212Q        LUBRAX ESSENCIAL SL 15W40 1-LITRO  01/06/2024   
6         1002  67213R  LUBRAX SUPERA 5W40 SN 1-LITRO SINTETICO  01/01/2024   
7         1002  67213R  LUBRAX SUPERA 5W40 SN 1-LITRO SINTETICO  01/02/2024   
8         1002  67213R  LUBRAX SUPERA 5W40 SN 1-LITRO SINTETICO  01/03/2024   
9         1002  67213R  LUBRAX SUPERA 5W40 SN 1-LITRO SINTETICO  01/04/2024   
10        1002  67213R  LUBRAX SUPERA 5W40 SN 1-LITRO SINTETICO  01/05/2024   
11        1002  67213R  LUBRAX SUPERA 5W40 SN 1-LITRO SINTETICO  01/06/2024   
12        1003  67215T     ESSENCIAL ALTA ROD. 25W50 SL 1-LITRO  01/01/2024   
13        1003  67215T     ESSENCIAL ALTA ROD. 25W50 SL 1-LITRO  01/02/2024   
14        1003  67215T     ESSENCIAL ALTA ROD. 25W50 SL 1-LITRO  01/03/2024   
15        1003  67215T     ESSENCIAL ALTA ROD. 25W50 SL 1-LITRO  01/04/2024   
16        1003  67215T     ESSENCIAL ALTA ROD. 25W50 SL 1-LITRO  01/05/2024   
17        1003  67215T     ESSENCIAL ALTA ROD. 25W50 SL 1-LITRO  01/06/2024   
18        1004  67216U       LUBRAX TOP TURBO 15W40 CI-41-LITRO  01/01/2024   
19        1004  67216U       LUBRAX TOP TURBO 15W40 CI-41-LITRO  01/02/2024   
20        1004  67216U       LUBRAX TOP TURBO 15W40 CI-41-LITRO  01/03/2024   
21        1004  67216U       LUBRAX TOP TURBO 15W40 CI-41-LITRO  01/04/2024   
22        1004  67216U       LUBRAX TOP TURBO 15W40 CI-41-LITRO  01/05/2024   
23        1004  67216U       LUBRAX TOP TURBO 15W40 CI-41-LITRO  01/06/2024   
24        1005  67218W        LUBRAX TECNO 15W40 SN SEMITB-200L  01/01/2024   
25        1005  67218W        LUBRAX TECNO 15W40 SN SEMITB-200L  01/02/2024   
26        1005  67218W        LUBRAX TECNO 15W40 SN SEMITB-200L  01/03/2024   
27        1005  67218W        LUBRAX TECNO 15W40 SN SEMITB-200L  01/04/2024   
28        1005  67218W        LUBRAX TECNO 15W40 SN SEMITB-200L  01/05/2024   
29        1005  67218W        LUBRAX TECNO 15W40 SN SEMITB-200L  01/06/2024   
30        1006  67219X       LUBRAX TECNO 15W40 SN SEMI3-LITROS  01/01/2024   
31        1006  67219X       LUBRAX TECNO 15W40 SN SEMI3-LITROS  01/02/2024   
32        1006  67219X       LUBRAX TECNO 15W40 SN SEMI3-LITROS  01/03/2024   
33        1006  67219X       LUBRAX TECNO 15W40 SN SEMI3-LITROS  01/04/2024   
34        1006  67219X       LUBRAX TECNO 15W40 SN SEMI3-LITROS  01/05/2024   
35        1006  67219X       LUBRAX TECNO 15W40 SN SEMI3-LITROS  01/06/2024   

    mes   ano  cost_real  qtd_real  cost_unit  dias_uteis  qtd_dia  \
0     1  2024          0         0          0          22  0,00000   
1     2  2024          0         0          0          19  0,00000   
2     3  2024          0         0          0          21  0,00000   
3     4  2024          0         0          0          22  0,00000   
4     5  2024          0         0          0          22  0,00000   
5     6  2024          0         0          0          20  0,00000   
6     1  2024          0         0          0          22  0,00000   
7     2  2024          0         0          0          19  0,00000   
8     3  2024          0         0          0          21  0,00000   
9     4  2024          0         0          0          22  0,00000   
10    5  2024          0         0          0          22  0,00000   
11    6  2024          0         0          0          20  0,00000   
12    1  2024      13556        19        713          22  0,86364   
13    2  2024      11046        16        690          19  0,84211   
14    3  2024       4858      

In [56]:
colunas_selecionadas = ['product_id', 'mes', 'ano', 'dias_uteis', 'qtd_real', 'qtd_dia_10000', 'cost_unit'] 

df_selecionado = df[colunas_selecionadas]

df_selecionado.head()

product_id  mes   ano  qtd_real  cost_unit
0        1001    1  2024         0          0
1        1002    1  2024         0          0
2        1003    1  2024        19        713
3        1004    1  2024       193        599
4        1005    1  2024         0          0

In [73]:
#colunas_selecionadas = ['product_id', 'mes', 'ano', 'dias_uteis', 'qtd_real', 'qtd_dia', 'cost_unit'] 
colunas_selecionadas = ['product_id', 'mes', 'ano', 'dias_uteis', 'qtd_real', 'qtd_dia_10000', 'varia_dia_media', 'varia_dia_abs'] 
#colunas_selecionadas = ['product_id', 'mes', 'ano', 'dias_uteis', 'qtd_real'] 

df_selecionado = df[colunas_selecionadas]
df_selecionado

product_id  mes   ano  dias_uteis  qtd_real  qtd_dia_10000  \
0           1001    1  2024          22         0              0   
1           1001    2  2024          19         0              0   
2           1001    3  2024          21         0              0   
3           1001    4  2024          22         0              0   
4           1001    5  2024          22         0              0   
...          ...  ...   ...         ...       ...            ...   
1771        1296    2  2024          19         0              0   
1772        1296    3  2024          21         0              0   
1773        1296    4  2024          22         0              0   
1774        1296    5  2024          22         0              0   
1775        1296    6  2024          20         1            500   

      varia_dia_media  varia_dia_abs  
0                   0              0  
1                   0              0  
2                   0              0  
3                   0              0  
4                   0              0  
...               ...            ...  
1771                0              0  
1772                0              0  
1773                0              0  
1774                0              0  
1775                0              0  

[1776 rows x 8 columns]

In [64]:
from sklearn.model_selection import train_test_split
import xgboost as xgb
from sklearn.metrics import mean_squared_error, accuracy_score

X = df_selecionado.drop(columns=['qtd_real'])
y = df_selecionado['qtd_real']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

dtrain = xgb.DMatrix(X_train, label=y_train)
dtest = xgb.DMatrix(X_test, label=y_test)

params = {
    'objective': 'reg:squarederror',  # Para problemas de regressão. Use 'binary:logistic' para classificação binária
    'max_depth': 6,
    'eta': 0.3,
    'eval_metric': 'rmse'
}

params = {
    'eta': 0.3,
    'gamma': 0.1,
    'min_child_weight': 1.0,
    'max_delta_step': 0.1,
    'subsample': 0.8,
    'colsample_bytree': 0.8,
    'colsample_bylevel': 0.8,
    'colsample_bynode': 0.8,
    'alpha': 0.1,
    'lambda': 1.0,
    'scale_pos_weight': 1.0,
    'objective': 'reg:squarederror',  # ou 'binary:logistic' para classificação binária
    'eval_metric': 'rmse'  # ou 'logloss' para classificação binária
}


# Treine o modelo
num_rounds = 100
bst = xgb.train(params, dtrain, num_rounds)

# Faça previsões no conjunto de teste
y_pred = bst.predict(dtest)

# Avalie o modelo (para regressão)
rmse = mean_squared_error(y_test, y_pred, squared=False)
print(f"RMSE: {rmse}")

# Avalie o modelo (para classificação, descomente as linhas abaixo e comente as linhas de regressão acima)
y_pred = (y_pred > 0.5).astype(int)
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy}")

# Exiba as primeiras previsões e os valores reais
print("\nPrevisões:")
print(y_pred[:10])
print(y_test.head(10))

RMSE: 463.97391783332966
Accuracy: 0.06460674157303371

Previsões:
[1 1 1 1 1 1 1 1 1 1]
65       0
940      0
1722    11
1698     0
799      6
1055     0
988      0
239      0
1555     2
1188     0
Name: qtd_real, dtype: int64


In [134]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor  # Para regressão
from sklearn.metrics import mean_squared_error, accuracy_score

X = df_selecionado.drop(columns=['qtd_real'])
y = df_selecionado['qtd_real']

# Divida os dados em conjuntos de treino e teste
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Crie o modelo de Random Forest
model = RandomForestRegressor(n_estimators=100, random_state=42)  # Para regressão
# model = RandomForestClassifier(n_estimators=100, random_state=42)  # Para classificação

# Treine o modelo
model.fit(X_train, y_train)

# Faça previsões no conjunto de teste
y_pred = model.predict(X_test)

# Avalie o modelo (para regressão)
rmse = mean_squared_error(y_test, y_pred, squared=False)
print(f"RMSE: {rmse}")

# Avalie o modelo (para classificação, descomente as linhas abaixo e comente as linhas de regressão acima)
# accuracy = accuracy_score(y_test, y_pred)
# print(f"Accuracy: {accuracy}")

# Exiba as primeiras previsões e os valores reais
print("\nPrevisões:")
print(y_pred[:10])
print("\nValores Reais:")
print(y_test.head(10))

reg_pred = {
    'product_id': [1003],
    'mes': [7],
    'ano': [2024],
    'dias_uteis': [23], 
    'qtd_dia_10000': [7484], 
    'varia_dia_media': [10586], 
    'varia_dia_abs': [10699],
}

df_reg_pred = pd.DataFrame(reg_pred)
print(df_reg_pred)
y_pred = model.predict(df_reg_pred)
print(y_pred)

RMSE: 33.82693321414399

Previsões:
[ 0.    0.   10.92  0.    6.    0.    0.    0.    2.    0.  ]

Valores Reais:
65       0
940      0
1722    11
1698     0
799      6
1055     0
988      0
239      0
1555     2
1188     0
Name: qtd_real, dtype: int64
   product_id  mes   ano  dias_uteis  qtd_dia_10000  varia_dia_media  \
0        1003    7  2024          23           7484            10586   

   varia_dia_abs  
0          10699  
[16.44]


In [87]:
#. 7484	10586	10699

reg_pred = {
    'product_id': [1003],
    'mes': [7],
    'ano': [2024],
    'dias_uteis': [23], 
    'qtd_dia_10000': [7484], 
    'varia_dia_media': [10586], 
    'varia_dia_abs': [10699],
}

df_reg_pred = pd.DataFrame(reg_pred)
df_reg_pred

product_id  mes   ano  dias_uteis  qtd_dia_10000  varia_dia_media  \
0        1003    7  2024          23           7484            10586   

   varia_dia_abs  
0          10699

In [88]:
y_pred = model.predict(df_reg_pred)
y_pred

array([16.44])

In [119]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier  # Para classificação
from sklearn.metrics import mean_squared_error, accuracy_score

X = df_selecionado.drop(columns=['qtd_real'])
y = df_selecionado['qtd_real']

# Divida os dados em conjuntos de treino e teste
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Crie o modelo de Random Forest
model = RandomForestRegressor(n_estimators=100, random_state=42)  # Para regressão
# model = RandomForestClassifier(n_estimators=100, random_state=42)  # Para classificação

# Treine o modelo
model.fit(X_train, y_train)

# Faça previsões no conjunto de teste
y_pred = model.predict(X_test)

# Avalie o modelo (para regressão)
rmse = mean_squared_error(y_test, y_pred, squared=False)
print(f"RMSE: {rmse}")

# Avalie o modelo (para classificação, descomente as linhas abaixo e comente as linhas de regressão acima)
# accuracy = accuracy_score(y_test, y_pred)
# print(f"Accuracy: {accuracy}")

# Exiba as primeiras previsões e os valores reais
print("\nPrevisões:")
print(y_pred[:10])
print("\nValores Reais:")
print(y_test.head(10))

RMSE: 33.82693321414399

Previsões:
[ 0.    0.   10.92  0.    6.    0.    0.    0.    2.    0.  ]

Valores Reais:
65       0
940      0
1722    11
1698     0
799      6
1055     0
988      0
239      0
1555     2
1188     0
Name: qtd_real, dtype: int64


In [120]:
reg_pred = {
    'product_id': [1003],
    'mes': [7],
    'ano': [2024],
    'dias_uteis': [23], 
    'qtd_dia_10000': [7484], 
    'varia_dia_media': [10586], 
    'varia_dia_abs': [10699],
}

df_reg_pred = pd.DataFrame(reg_pred)
y_pred = model.predict(df_reg_pred)
random_forest_classifier = y_pred
y_pred

array([16.44])

In [105]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import BayesianRidge
from sklearn.metrics import mean_squared_error

X = df_selecionado.drop(columns=['qtd_real'])
y = df_selecionado['qtd_real']

# Divida os dados em conjuntos de treino e teste
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Crie o modelo de Regressão de Bayes
model = BayesianRidge()

# Treine o modelo
model.fit(X_train, y_train)

# Faça previsões no conjunto de teste
y_pred = model.predict(X_test)

# Avalie o modelo usando RMSE para regressão
rmse = mean_squared_error(y_test, y_pred, squared=False)
print(f"RMSE: {rmse}")

# Exiba as primeiras previsões e os valores reais
print("\nPrevisões:")
print(y_pred[:10])
print("\nValores Reais:")
print(y_test.head(10))

RMSE: 28.61005260750045

Previsões:
[ 1.00818668  0.98802777 11.30000226  0.97041583 -9.18229022  0.98531751
  0.98691896  1.00416725  2.52846385  0.98219691]

Valores Reais:
65       0
940      0
1722    11
1698     0
799      6
1055     0
988      0
239      0
1555     2
1188     0
Name: qtd_real, dtype: int64


In [107]:
reg_pred = {
    'product_id': [1003, 1003, 1003],
    'mes': [6, 7, 8],
    'ano': [2024, 2024, 2024],
    'dias_uteis': [20, 23, 22], 
    'qtd_dia_10000': [6500, 7484, 7484], 
    'varia_dia_media': [6217, 10586, 10586], 
    'varia_dia_abs': [5652, 10699, 10699],
}

df_reg_pred = pd.DataFrame(reg_pred)
y_pred = model.predict(df_reg_pred)
y_pred

array([13.43975595, 16.65460004, 16.65456282])

In [68]:
y_test.head()

65       0
940      0
1722    11
1698     0
799      6
Name: qtd_real, dtype: int64

In [69]:
df_selecionado

product_id  mes   ano  dias_uteis  qtd_real  qtd_dia_10000  \
0           1001    1  2024          22         0              0   
1           1001    2  2024          19         0              0   
2           1001    3  2024          21         0              0   
3           1001    4  2024          22         0              0   
4           1001    5  2024          22         0              0   
...          ...  ...   ...         ...       ...            ...   
1771        1296    2  2024          19         0              0   
1772        1296    3  2024          21         0              0   
1773        1296    4  2024          22         0              0   
1774        1296    5  2024          22         0              0   
1775        1296    6  2024          20         1            500   

      varia_dia_media  varia_dia_abs  
0                   0              0  
1                   0              0  
2                   0              0  
3                   0              0  
4                   0              0  
...               ...            ...  
1771                0              0  
1772                0              0  
1773                0              0  
1774                0              0  
1775                0              0  

[1776 rows x 8 columns]

In [121]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

# Separe as features e o alvo
X = df_selecionado.drop(columns=['qtd_real'])
y = df_selecionado['qtd_real']

# Divida os dados em conjuntos de treino e teste
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Crie o modelo de Regressão Linear
model = LinearRegression()

# Treine o modelo
model.fit(X_train, y_train)

# Faça previsões no conjunto de teste
y_pred = model.predict(X_test)

# Avalie o modelo usando RMSE para regressão
rmse = mean_squared_error(y_test, y_pred, squared=False)
print(f"RMSE: {rmse}")

# Exiba as primeiras previsões e os valores reais
print("\nPrevisões:")
print(y_pred[:10])
print("\nValores Reais:")
print(y_test.head(10))

RMSE: 28.273205161357865

Previsões:
[-1.85509401  4.33371805 13.81650322  3.49772078 -7.93366957 -2.37233941
  4.30863949 -1.94600381 -4.5890766   3.76418053]

Valores Reais:
65       0
940      0
1722    11
1698     0
799      6
1055     0
988      0
239      0
1555     2
1188     0
Name: qtd_real, dtype: int64


In [123]:
reg_pred = {
    'product_id': [1003],
    'mes': [7],
    'ano': [2024],
    'dias_uteis': [23], 
    'qtd_dia_10000': [7484], 
    'varia_dia_media': [10586], 
    'varia_dia_abs': [10699],
}

df_reg_pred = pd.DataFrame(reg_pred)
y_pred = model.predict(df_reg_pred)
linear_regression = y_pred
y_pred

array([24.07788873])

In [96]:
import numpy as np
import pandas as pd
import statsmodels
from statsmodels.tsa.arima.model import ARIMA
from statsmodels.tsa.statespace.sarimax import SARIMAX
#from statsmodels.tsa.stattools import adfuller 

In [97]:
def Arima_Media_Movel_Autoregressiva(data):
    
    # ARIMA Media Movel Autoregressiva             +++++++++++++++++++++
    
    # fit modelo
    model = ARIMA(data, order=(2, 0, 1))
    model_fit = model.fit()

    previ = model_fit.predict(len(data), len(data))
    return(previ)


In [98]:
def Arima_Media_Movel_Integrada_Autoregressiva(data):
    
    # ARIMA Media Movel Integrada Autoregressiva  +++++++++++++++++++++

    # fit modelo
    model = ARIMA(data, order=(1, 0, 1))
    model_fit = model.fit()

    previ = model_fit.predict(len(data), len(data))
    return(previ)

In [99]:
def Sarima_Media_Movel_Integrada_Autoregressiva(data):
    
    # SARIMA Sazonal Media Movel Integrada Autoregressiva  +++++++++++++++++++++

    # fit modelo
    model = SARIMAX(data, order=(1, 1, 1), seasonal_order=(0, 1, 0, 3))
    model_fit = model.fit(disp=False)

    previ = model_fit.predict(len(data), len(data))
    return(previ)
    #data = np.append(data, previ, axis = None)

In [100]:
data=[19, 16, 7, 21, 23, 13]
data

[19, 16, 7, 21, 23, 13]

In [101]:
Arima_Media_Movel_Autoregressiva(data)

/opt/anaconda3/lib/python3.11/site-packages/statsmodels/base/model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "


array([10.11980514])

In [102]:
Arima_Media_Movel_Integrada_Autoregressiva(data)

array([15.88157405])

In [103]:
Sarima_Media_Movel_Integrada_Autoregressiva(data)

/opt/anaconda3/lib/python3.11/site-packages/statsmodels/tsa/statespace/sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for ARMA and trend. All parameters except for variances will be set to zeros.
  warn('Too few observations to estimate starting parameters%s.'


array([26.75832585])

In [132]:
z1 = Arima_Media_Movel_Autoregressiva(data)
z2 = Arima_Media_Movel_Integrada_Autoregressiva(data)
z3 = Sarima_Media_Movel_Integrada_Autoregressiva(data)

x = [z1, z2, z3]

val_min = min(x)
val_max = max(x)
val_meio = val_min

if val_max != z1:
    if val_meio < z1:
        val_meio = z1

if val_max != z2:
    if val_meio < z2:
        val_meio = z2

if val_max != z3:
    if val_meio < z3:
        val_meio = z3       

print('Previsão para o próximos mês')
print('')
print('Dados das quantidade dos últimos 6 meses...:', data)
print('Arima_Media_Movel_Autoregressiva...........:', z1)
print('Arima_Media_Movel_Integrada_Autoregressiva :', z2)
print('Sarima_Media_Movel_Integrada_Autoregressiva:', z3)
        
x1 = val_max - val_min
x2 = val_max - val_meio
x3 = (x1 + x2) * 2

if x3 == 0:
    resultado = val_max
else:
    resultado = ((val_max * x3) + (val_meio * x1) + (val_min * x2)) / (x1 + x2 + x3)

print('')
print('Res. Hoje .................................:', resultado)
print('')
print('random_forest_classifier...................:', random_forest_classifier)
print('linear_regression..........................:', linear_regression)

Previsão para o próximos mês

Dados das quantidade dos últimos 6 meses...: [19, 16, 7, 21, 23, 13]
Arima_Media_Movel_Autoregressiva...........: [10.11980514]
Arima_Media_Movel_Integrada_Autoregressiva : [15.88157405]
Sarima_Media_Movel_Integrada_Autoregressiva: [26.75832585]

Res. Hoje .................................: [22.37353531]

random_forest_classifier...................: [16.44]
linear_regression..........................: [24.07788873]


/opt/anaconda3/lib/python3.11/site-packages/statsmodels/base/model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
