In [28]:
tamanho = 8.47826

In [29]:
print("Tamanho = %d cm" % tamanho)

Tamanho = 8 cm


In [30]:
print("Tamanho = %i cm" % tamanho)

Tamanho = 8 cm


In [31]:
print("Tamanho = %f cm" % tamanho)

Tamanho = 8.478260 cm


In [37]:
print("Tamanho = %4.2f cm" % tamanho)

Tamanho = 8.48 cm


In [41]:
print("Tamanho = %.4f cm" % tamanho)

Tamanho = 8.4783 cm


In [42]:
print("Tamanho = %2.10f cm" % tamanho)

Tamanho = 8.4782600000 cm


In [35]:
print("Tamanho = %.10f cm" % tamanho)

Tamanho = 8.4782600000 cm


In [1]:
a=[]
a.append([1,2,3,4,5])
a.append([2,3,4,5,6])

In [8]:
import numpy as py

In [5]:
a

[[1, 2, 3, 4, 5], [2, 3, 4, 5, 6]]

In [6]:
a[0]+a[1]

[1, 2, 3, 4, 5, 2, 3, 4, 5, 6]

In [9]:
py.add(a[0], a[1])

array([ 3,  5,  7,  9, 11])

In [11]:
py.subtract(a[0], a[1])

array([-1, -1, -1, -1, -1])

In [12]:
py.subtract(a[0], a[0]) 

array([0, 0, 0, 0, 0])

In [18]:
x = py.subtract(a[0], a[1]) 

In [28]:
x

array([-1, -1, -1, -1, -1])

In [29]:
bool(x.all())

True

In [34]:
y = []
y.append([1,1,1,1,0])

In [178]:
y = [1, 2, 3]
x = [1,0,0]

z = py.multiply(x, y)
z

array([1, 0, 0])

In [4]:
x = 1
y = 2

def teste():
    d = 30
    print(d)
    return(d)

print(x)
print(y)
r = teste()
print(r)
print(d)

1
2
30
30


NameError: name 'd' is not defined

In [179]:
z.any()

True

In [170]:
z = py.multiply(y[0], a[1])
z

array([2, 3, 4, 5, 6])

In [171]:
bool(z.any())

True

In [195]:
import numpy as py

valor = -1

nt_val = py.array([200, 100, 50, 20, 10]) # Valor de face das Notas

notas_qtd = py.array([1, 2, 10, 10, 20]) # Quantidade de Notas disponíveis na abertura

achou = 0

# Define Notas

def define_notas(valor, resultado):
    
    valor_roda = valor
    
    for i in range(len(resultado)):
        if resultado[i] < 0:
            if notas_qtd[i] != 0:
                resultado[i] = valor_roda // nt_val[i]
                
                if resultado[i] <= notas_qtd[i]:         
                    valor_roda = valor_roda % nt_val[i]
                else:
                    resultado[i] = notas_qtd[i]
                    valor_roda = valor_roda -  resultado[i] * nt_val[i] 
            else:
                resultado[i] = 0
        else:
            valor_roda = valor_roda - (resultado[i] * nt_val[i])

    return(resultado)

def verifica_total(valor_teste, valor_total):
    soma = 0
    for i in range(len(valor_total)):
        soma = soma + valor_total[i] * nt_val[i]
    
    if soma != valor_teste:
        return(False)
    else:
        return(True)

# INICIO

escolha = []

print("Notas: ", nt_val)
print("Qtd Disponivel: ", notas_qtd)

while valor:
    valor = input("Valor do saque: ")
    valor = float(valor)
    achou = 0
    
    resultado = py.array([-1,-1,-1,-1,-1])

    while resultado.any() and valor:
        volta = define_notas(valor, resultado)
    
        if not verifica_total(valor, volta):
            break
    
        x = py.subtract(notas_qtd, volta)

        tst_qtd = True
        for i in range(len(x)):
            if x[i] < 0:
                tst_qtd = False
                
        if tst_qtd:
            print(f"Opcao: {achou + 1} Valor: {valor} | 200: {volta[0]} | 100: {volta[1]} | 50: {volta[2]} | 20: {volta[3]} | 10: {volta[4]}")
            escolha.append([volta[0],volta[1],volta[2],volta[3],volta[4]])
            achou = achou + 1
        
        conta = 1
        for i in range(len(resultado)):
            if resultado[i] > 0 and conta:
                resultado[i] = resultado[i] - 1
                conta = 0
            elif not (resultado[i] == 0 and conta):
                resultado[i] = -1

    if not achou:
        print(f"O valor solicitado de R$ {valor:.2f} não é possível. \nFavor escolher outro valor.")
        if not valor:
            valor = -1
    else:
        if achou:
            if achou > 1:
                opcao = input("\nEscolha a opçao: ")
                opcao = int(opcao)
            else:
                opcao = 1
                
            if opcao < 0 or opcao > achou:
                print("Opcao inválida, optando pela primeira opcao: ")
                opcao = 0
            else:
                opcao = opcao - 1
                
            print(f"\nValor: {valor} | 200: {escolha[opcao][0]} | 100: {escolha[opcao][1]} | 50: {escolha[opcao][2]} | 20: {escolha[opcao][3]} | 10: {escolha[opcao][4]}")
            notas_qtd = py.subtract(notas_qtd, escolha[opcao])
            print("\nNotas: ", nt_val)
            print("Qtd Disponivel: ", notas_qtd, "\n")
            
    escolha = []
    if not notas_qtd.any():
        print("Caixa Eletrônico sem DINHEIRO")
        break
        


Notas:  [200 100  50  20  10]
Qtd Disponivel:  [ 1  2 10 10 20]


Valor do saque:  800


Opcao: 1 Valor: 800.0 | 200: 1 | 100: 2 | 50: 8 | 20: 0 | 10: 0
Opcao: 2 Valor: 800.0 | 200: 0 | 100: 2 | 50: 10 | 20: 5 | 10: 0
Opcao: 3 Valor: 800.0 | 200: 0 | 100: 1 | 50: 10 | 20: 10 | 10: 0
Opcao: 4 Valor: 800.0 | 200: 0 | 100: 0 | 50: 10 | 20: 10 | 10: 10
Opcao: 5 Valor: 800.0 | 200: 0 | 100: 0 | 50: 9 | 20: 10 | 10: 15
Opcao: 6 Valor: 800.0 | 200: 0 | 100: 0 | 50: 8 | 20: 10 | 10: 20



Escolha a opçao:  3



Valor: 800.0 | 200: 0 | 100: 1 | 50: 10 | 20: 10 | 10: 0

Notas:  [200 100  50  20  10]
Qtd Disponivel:  [ 1  1  0  0 20] 



Valor do saque:  10


Opcao: 1 Valor: 10.0 | 200: 0 | 100: 0 | 50: 0 | 20: 0 | 10: 1

Valor: 10.0 | 200: 0 | 100: 0 | 50: 0 | 20: 0 | 10: 1

Notas:  [200 100  50  20  10]
Qtd Disponivel:  [ 1  1  0  0 19] 



Valor do saque:  290


Opcao: 1 Valor: 290.0 | 200: 1 | 100: 0 | 50: 0 | 20: 0 | 10: 9
Opcao: 2 Valor: 290.0 | 200: 0 | 100: 1 | 50: 0 | 20: 0 | 10: 19



Escolha a opçao:  2



Valor: 290.0 | 200: 0 | 100: 1 | 50: 0 | 20: 0 | 10: 19

Notas:  [200 100  50  20  10]
Qtd Disponivel:  [1 0 0 0 0] 



Valor do saque:  100


O valor solicitado de R$ 100.00 não é possível. 
Favor escolher outro valor.


Valor do saque:  300


O valor solicitado de R$ 300.00 não é possível. 
Favor escolher outro valor.


Valor do saque:  200


Opcao: 1 Valor: 200.0 | 200: 1 | 100: 0 | 50: 0 | 20: 0 | 10: 0

Valor: 200.0 | 200: 1 | 100: 0 | 50: 0 | 20: 0 | 10: 0

Notas:  [200 100  50  20  10]
Qtd Disponivel:  [0 0 0 0 0] 

Caixa Eletrônico sem DINHEIRO


In [54]:
import json
 
# Opening JSON file
f = open('events_data.json')
 
# returns JSON object as 
# a dictionary
data = json.load(f)

In [55]:
import pandas as pd
from pandas import json_normalize

In [57]:
df = json_normalize(data['MEIA MARATONA DE VILA VELHA']) 

In [58]:
df

name        data             city  \
0  MEIA MARATONA DE VILA VELHA  29/10/2023  Vila Velha - ES   

                                         url_details  \
0  http://www.chiptiming.com.br/resultados/meiavi...   

  categories.5KM.GERAL FEMININO.name categories.5KM.GERAL FEMININO.url  \
0                     GERAL FEMININO   /resultados/detalhes/2802615619   

              categories.5KM.GERAL FEMININO.athletes  \
0  [{'highlight_place': '1', 'number': '5229', 'n...   

  categories.5KM.GERAL MASCULINO.name categories.5KM.GERAL MASCULINO.url  \
0                     GERAL MASCULINO    /resultados/detalhes/2802615615   

             categories.5KM.GERAL MASCULINO.athletes  ...  \
0  [{'highlight_place': '1', 'number': '5947', 'n...  ...   

            categories.10KM.GERAL MASCULINO.athletes  \
0  [{'highlight_place': '1', 'number': '1735', 'n...   

  categories.21KM.GERAL FEMININO.name categories.21KM.GERAL FEMININO.url  \
0                      GERAL FEMININO    /resultados/detalhes/2802615650   

             categories.21KM.GERAL FEMININO.athletes  \
0  [{'highlight_place': '1', 'number': '2206', 'n...   

  categories.21KM.GERAL MASCULINO.name categories.21KM.GERAL MASCULINO.url  \
0                      GERAL MASCULINO     /resultados/detalhes/2802615640   

            categories.21KM.GERAL MASCULINO.athletes  \
0  [{'highlight_place': '1', 'number': '2639', 'n...   

  categories.21KM.DEFICIENTE MASCULINO.name  \
0                      DEFICIENTE MASCULINO   

  categories.21KM.DEFICIENTE MASCULINO.url  \
0          /resultados/detalhes/2802615622   

       categories.21KM.DEFICIENTE MASCULINO.athletes  
0  [{'highlight_place': '1', 'number': '299', 'na...  

[1 rows x 31 columns]

In [65]:
df['categories.5KM.GERAL FEMININO.athletes'][0]

AttributeError: 'list' object has no attribute 'head'

In [71]:
dados = df.explode(column='categories.21KM.GERAL MASCULINO.athletes', ignore_index=True)
# dados

In [72]:
dados['categories.21KM.GERAL MASCULINO.athletes'][0]

{'highlight_place': '1',
 'number': '2639',
 'name': 'Tiago Vasconcelos Dos Santos',
 'gender': 'M',
 'age': '36',
 'age_group': 'M3539',
 'team': '-',
 'timing': '01:15:51',
 'liquid_timing': '01:15:47',
 'rhythm': '03:36'}

In [75]:
pd.json_normalize(data=dados['categories.21KM.GERAL MASCULINO.athletes'])

highlight_place number                          name gender age age_group  \
0                 1   2639  Tiago Vasconcelos Dos Santos      M  36     M3539   
1                 2   2885        Eber Moreira Rodrigues      M  42     M4044   
2                 3   2686   adilton da conceicao santos      M  50     M5054   
3                 4   2791   Weverton Rodovalho Da Costa      M  29     M2529   
4                 5   2863    Alessandro Quirino Ignacio      M  34     M3034   
..              ...    ...                           ...    ...  ..       ...   
306             307   2986            Pablo Lobato Ramos      M  46     M4549   
307             308   2895          Jayme Teixeira Bessa      M  40     M4044   
308             309     23        Jayme Oliveira Hilario      M  39     M3539   
309             310   2664        Eberty Dias De Almeida      M  35     M3539   
310             311   2799           Jose Weslay Celeste      M  62     M6064   

    team    timing liquid_timing rhythm  
0      -  01:15:51      01:15:47  03:36  
1      -  01:22:14      01:22:08  03:54  
2      -  01:24:09      01:24:03  04:00  
3      -  01:24:20      01:24:14  04:00  
4      -  01:26:17      01:26:12  04:06  
..   ...       ...           ...    ...  
306   43  02:48:54      02:48:36  08:01  
307   57  02:50:38      02:49:10  08:03  
308   70  02:52:40      02:50:42  08:07  
309   71  02:52:52      02:52:06  08:11  
310    7  02:54:34      02:53:55  08:16  

[311 rows x 10 columns]

In [73]:
for i in dados['categories.21KM.GERAL MASCULINO.athletes']:
    print(i['highlight_place'], i['name'], i['age'], i['gender'], i['rhythm'], i['liquid_timing'])

1 Tiago Vasconcelos Dos Santos 36 M 03:36 01:15:47
2 Eber Moreira Rodrigues 42 M 03:54 01:22:08
3 adilton da conceicao santos 50 M 04:00 01:24:03
4 Weverton Rodovalho Da Costa 29 M 04:00 01:24:14
5 Alessandro Quirino Ignacio 34 M 04:06 01:26:12
6 Matheus Rosa 27 M 04:08 01:27:02
7 Raphael Carneiro 20 M 04:11 01:28:08
8 Raphael Ambrozini Santos 33 M 04:14 01:29:02
9 Rafael Pereira Pizzani Rodrigues 29 M 04:15 01:29:20
10 Samuel Vergilio De Souza 42 M 04:18 01:30:34
11 Luiz Angelo Mazzocco Marques 35 M 04:23 01:32:04
12 Claudio Fernandes 53 M 04:23 01:32:15
13 Rodrigo Davini 44 M 04:24 01:32:26
14 Gilgleisson Demonel 39 M 04:29 01:34:27
15 Gabriel Temporim Hemerly 25 M 04:30 01:34:45
16 Leonardo Rocha 42 M 04:33 01:35:44
17 Elizeu Nascimento Falcao Goncalves 46 M 04:33 01:35:49
18 Jadisson Ferreira Da Silva 37 M 04:36 01:36:44
19 Humberto Carlos Da Silva 54 M 04:40 01:38:05
20 Wallace Borlot 44 M 04:40 01:38:18
21 Mario Monteiro Vasconcelos 34 M 04:41 01:38:25
22 Mauro Da Conceicao Silva

In [7]:
import math

In [24]:
def truncar(v, t):
    t = 10 ^ t
    return(int(v * t) / t)

In [28]:
y = 999999.999999999
x = int(y * 100) / 100
print(y, x)
print('{:.2f}'.format(x))

999999.999999999 999999.99
999999.99


In [26]:
y
u = truncar(y, 1)

In [27]:
print (y , u)

999999.99 999999.9090909091


In [85]:
x = 0
while x <= 50:
    x += 1
    i = 1
    conta = 0
    while i <= 50:
        i += 1
        if (x % i == 0):
            conta += 1
        
    if conta == 1:
        print(f"o número {x} é primo")

o número 2 é primo
o número 3 é primo
o número 5 é primo
o número 7 é primo
o número 11 é primo
o número 13 é primo
o número 17 é primo
o número 19 é primo
o número 23 é primo
o número 29 é primo
o número 31 é primo
o número 37 é primo
o número 41 é primo
o número 43 é primo
o número 47 é primo


In [82]:
for x in range(2, 50):
    conta = 0
    for i in range(2, 50):
        if (x % i == 0):
            conta += 1
        
    if conta == 1:
        print(f"o número {x} é primo")

o número 2 é primo
o número 3 é primo
o número 5 é primo
o número 7 é primo
o número 11 é primo
o número 13 é primo
o número 17 é primo
o número 19 é primo
o número 23 é primo
o número 29 é primo
o número 31 é primo
o número 37 é primo
o número 41 é primo
o número 43 é primo
o número 47 é primo


In [77]:
x = int(input("inicio "))
conta = 0

for i in range(2, 1000):
    if (x % i == 0):
        conta += 1
        
if conta == 1:
    print(f"o número {x} é primo")
else:
    print(f"o número {x} não é primo")

inicio  37


o número 37 é primo


In [62]:
x = int(input("inicio "))
y = int(input("final "))

for i in range(x, (y + 1)):
    print(i)

inicio  3
final  8


3
4
5
6
7
8


In [41]:
x = [11, 20, 34, 48, 53]

for i in range(len(x)):
    print(i, x[i])

0 11
1 20
2 34
3 48
4 53


In [47]:
for i in range(3, 9):
    print(i)

3
4
5
6
7
8


In [86]:
x = input("tri ")

tri  1 2 3 


In [98]:
x = input("tri ")
tri = []
print(x)
pos = 0
for i in x.split():
    tri.append(int(i))
tri.sort(reverse = True)
print(tri)
if (tri[0] ^ 2) == ((tri[1] ^ 2) + (tri[2] ^ 2)):
    print("triangulo retangulo")

tri  3 4 5


3 4 5
[5, 4, 3]
triangulo retangulo


In [118]:
x = int(input("Taboada: "))
for i in range(1, 11): print(f"{i:2.0f} x {x:2.0f} = {(i * x):2.0f}")

Taboada:  3


 1 x  3 =  3
 2 x  3 =  6
 3 x  3 =  9
 4 x  3 = 12
 5 x  3 = 15
 6 x  3 = 18
 7 x  3 = 21
 8 x  3 = 24
 9 x  3 = 27
10 x  3 = 30


In [101]:
for i in range(1, 11):
    print(i)

1
2
3
4
5
6
7
8
9
10


In [397]:
lado = [float(y) for y in input("Digite os tres lados de um triangulo").split()]

lado.sort(reverse = True)
if (lado[1] + lado[2]) <= lado[0]: print("Não é um Triangulo.")
else:
    if (lado[0] ** 2) == ((lado[1] ** 2) + (lado[2] ** 2)): tipo = "Retangulo"
    elif lado[0] == lado[1] == lado[2]: tipo = "Equilatero"
    elif (lado[0] == lado[1]) or (((lado[1] + lado[2])/2) == lado[2]): tipo = "Isosceles"
    else: tipo = "Escaleno"
    
    print("É um Triangulo", tipo)

Digite os tres lados de um triangulo 3 4 5


É um Triangulo Retangulo


In [375]:
lado = [2, 1, 1]
(lado[0] == lado[1]) or (((lado[1] + lado[2])/2) == lado[2])

True

In [396]:
lado

In [303]:
tipo = "Escaleno"
for i in range(3):
    for j in range((i + 1), 3):
        if lado[i] == lado[j]:
            tipo = "Isosceles"
            break
print(tipo)

Isosceles


In [ ]:
for i in range(3):
    for j in range((i + 1), 3):
        if (lado[i] == lado[j]:
            tipo = "Isosceles"
            break

In [127]:
a = [1, 2, 3]
print(a, a[0], a[1], a[2])
a.append(4)
print(a, a[0], a[1], a[2], a[3])

[1, 2, 3] 1 2 3
[1, 2, 3, 4] 1 2 3 4


In [132]:
x = input("digite os tres lados de um triangulo")

digite os tres lados de um triangulo 34 56 89


In [140]:
print(x, type(x))
x.split()[2]

34 56 89 <class 'str'>


'89'

In [137]:
x[0]

'3'

In [131]:
lado = []

for i in x.split():
    lado.append(int(i))

print(lado)

[]
[3]
[3, 4]
[3, 4, 5]


In [129]:
x

'3 4 5'

In [188]:
nome_completo = input("nome: ")

nome:  Luiz Wanderley Tavares


In [189]:
nome_completo


'Luiz Wanderley Tavares'

In [190]:
no_teste = nome_completo.split()
no_teste

['Luiz', 'Wanderley', 'Tavares']

In [191]:
no_tamanho = len(no_teste)
no_tamanho

3

In [192]:
nome = no_teste[0]
sobrenome = no_teste[(no_tamanho - 1)]

In [193]:
print(nome, sobrenome)

Luiz Tavares


In [194]:
nome_meio = ""
for i in range(no_tamanho):
    if i == 0:
        nome = no_teste[i]
    elif i == (no_tamanho - 1):
        sobrenome = no_teste[i]
    else:
        nome_meio = nome_meio + no_teste[i][0] + " "

print(nome)
print(nome_meio)
print(sobrenome)

Luiz
W 
Tavares


In [195]:
no_teste

['Luiz', 'Wanderley', 'Tavares']

In [196]:
a = []
a

[]

In [197]:
a.append(1)
a

[1]

In [198]:
a.append(11)
a

[1, 11]

In [199]:
a[0]

1

In [200]:
a[1]

11

In [202]:
a.append(8)
a[2]

8

In [261]:
a = ['1', '2', '3']
s = a.astype('float64')

AttributeError: 'list' object has no attribute 'astype'

In [206]:
for i in a:
    print(i)

1
11
8


In [267]:
a = "1 2 3"
int(a.split())
a

TypeError: int() argument must be a string, a bytes-like object or a number, not 'list'

In [354]:
# digitar os numeros separados por espaço. Exemplo: 6 8 5 9.6 7

n = input("Notas: ").split()
m = (sum([float(x) for x in n])) / len(n)
if m < 6: n = "Reprovado"
else: n = "Aprovado"
print(n, f"com média {m:.1f}")

Notas:  1 2 3


Reprovado com média 2.0


In [279]:
x = input("Notas: ").split()

Notas:  3 4 65 


In [280]:
x

['3', '4', '65']

In [287]:
n = input("Números: ").split()
print(f"Média..: {((sum([float(x) for x in n])) / len(n)): .1f}")

Números:  4 5 3 


Média..:  4.0


In [393]:
lado1, lado2, lado3 = map(int, input("Digite os três lados separados por espaços: ").split())
if lado1 + lado2 > lado3 and lado1 + lado3 > lado2 and lado2 + lado3 > lado1:
    if lado1 == lado2 == lado3:
        print("Com esses lados o triângulo é EQUILÁTERO")
    elif lado1 == lado2 or lado1 == lado3 or lado2 == lado3:
        print("Com esses lados o triângulo é ISÓCELES")
    else:
        print("Com esses lados o triângulo é ESCALENO")
else:
    print("Não forma um triângulo")

Digite os três lados separados por espaços:  4 1 4


Com esses lados o triângulo é ISÓCELES
